#pragma once
	

#define HALF_HOUR 30
#define COLOR_BLACK 192

#define SCREEN_WIDTH 144
#define SCREEN_HEIGHT 168
#define TIME_LAYER_TOP_MARGIN -10
#define TIME_LAYER_HEIGHT 40
#define HEADER_BACKGROUND_HEIGHT 40
#define ICON_SIZE 36
#define TEXT_HEIGHT 20
#define MAX_STATS 4
#define LOADING_TEXT_HEIGHT 40
#define LOADING_TEXT "Loading..."

#define FIRST_ICON 0
#define FIRST_COLOR 1
#define FIRST_VALUE 2
#define SECOND_ICON 3
#define SECOND_COLOR 4
#define SECOND_VALUE 5
#define THIRD_ICON 6
#define THIRD_COLOR 7
#define THIRD_VALUE 8
#define FOURTH_ICON 9
#define FOURTH_COLOR 10
#define FOURTH_VALUE 11
#define BACKGROUND_COLOR 12
#define VIBRATION 13
